int1 = int(input("Enter an integer"))
print("The integer you entered is:", int1)
print(type(int1))
float1 = float(input("Enter a float value"))
print("The float value you entered is:", float1)
print(type(float1))
