print(10>2)
print(2>10)
print(2<10)
print(10<2)
print(7>=7)
print(5>=7)
print(9>=7)
print(5<=5)
print(9<=5)
print(3<=5)
print(5!=8)
print(5!=5)
print(3==3)
print(7==3)
print("hello"=="world")
print("hello"=="hello")
print("hello"!="world")
print("hello"!="hello")
print(4.0==4)
print(str(4)==4)
print("hello"!=7)
print(True and True)
print(True and False)
print("hello"=="hello" and "hello"!="world")
